### PR TITLE
Monolith artifact-builder dockerfile

### PR DESCRIPTION
**Pull request by chemikadze**
Dockerfile that is used in https://github.com/qubell-bazaar/component-war-docker/pull/4

### CODE REVIEW

**Comment by chemikadze** [comment]
@rtimush take a look

**Comment by graven** [comment]
I wonder if there is a market for a utility that creates a single docker
image out of a fixed topology.

Stan

**Comment by rtimush** [comment]
It is not a generic artifact builder, it can build only war archives.

**Comment by rtimush** [comment]
No other objections

**Comment by chemikadze** [comment]
@rtimush I've added ability to specify artifact pattern and "war" references. Dependent manifest PR is updated too.

**Pull request merged**
