### PR TITLE
Added scheduled commands which provide activity log examples

### PR DESCRIPTION
**Pull request by netvl**
`schedule` command provide an example of how activity log pushing works. It schedules a "task" with some delay which then gets "executed" in the health-check script, which results to pushing a line to the activity log.

### CODE REVIEW

**Comment by netvl** [comment]
@dornatsky, please confirm.

**Comment by dornatsky** [comment]
Wow, what a poorly named repo. Can we mention in the readme file that this is about our scripting service?

**Comment by netvl** [comment]
It's not only about scripting service. Some (actually, most) dockerfiles are for other things.

**Comment by netvl** [comment]
Thanks!

**Pull request merged**
